### ISSUE TITLE
我觉得利用basemodel校验用户的配置文件不应该去掉

### ISSUE THREAD

**Issue by m986883511** [AnsGoo/PyPicGo#4]
一开始的代码在这里 https://github.com/AnsGoo/PyPicGo/commit/1d62237a3b1ad74c3cb176b8e87c66c3e7f5639d/core/config.py#r126889427

基于什么考虑现在去掉了呢

**Comment by m986883511** [comment]
pipenv并不好用，miniconda3才是最牛的（工具吹了），补充下原始的requirement.txt吧

**Comment by m986883511** [comment]
有个同学说需要web版本，我也挺需要的，我目前使用obsidian的图传插件是结合https://github.com/Molunerfinn/PicGo 使用的，但是它不支持socket5代理，由于我不会改js，不会改他的代码，每次得开全局代理，用得我很难受。

不过我不需要界面，需要的是一个纯后台的api服务，这个我自己可以搞定，拜读了一下您的代码，写的很棒，代码框架是参考picgo-core的吗？我只会python，看不懂js，哈哈

**Comment by AnsGoo** [comment]
> 一开始的代码在这里 [1d62237/core/config.py#r126889427](https://github.com/AnsGoo/PyPicGo/commit/1d62237a3b1ad74c3cb176b8e87c66c3e7f5639d/core/config.py#r126889427)
> 
> 基于什么考虑现在去掉了呢

因为Pydantic 太大了,验证与否对于一个插件包意义不大，如果能写成插件库，相信大家都是经过深思熟虑的验证，pydantic 更多的是对用户的输入进行验证

**Comment by AnsGoo** [comment]
> pipenv并不好用，miniconda3才是最牛的（工具吹了），补充下原始的requirement.txt吧



> 有个同学说需要web版本，我也挺需要的，我目前使用obsidian的图传插件是结合https://github.com/Molunerfinn/PicGo 使用的，但是它不支持socket5代理，由于我不会改js，不会改他的代码，每次得开全局代理，用得我很难受。
> 
> 不过我不需要界面，需要的是一个纯后台的api服务，这个我自己可以搞定，拜读了一下您的代码，写的很棒，代码框架是参考picgo-core的吗？我只会python，看不懂js，哈哈

本来我也想用`picgo`，但是他太大了，picgo有UI页面的前提是后台有一个常驻进程，监听用户的行为作出反应，我觉得太笨重了，当时用`typora`做文档编辑的时候，它本身支持用命令的方式调用服务，然后就写了一个命令行工具，需要的时候拉起，不需要的时候当他不存在

`picgo`的源码没看过，但是既然他是一个Web服务，那么肯定离不开`洋葱模型`,所谓的文件上传插件，无非是在洋葱的外围包一层处理数据的行为，数据入口我们称之为前置插件，数据出口我们称之为后置插件

前置插件用来在数据上传前进行加工，比如图片压缩、打水印
后置插件用户处理数据上传完成之后如何返回给用户需要的数据，例如获取图片图床真实的地址，将图片地址写进用户剪切板，向用户提示图片上传成功

**Comment by AnsGoo** [comment]
> pipenv并不好用，miniconda3才是最牛的（工具吹了），补充下原始的requirement.txt吧

讨论用什么构建工具意义不大

**Comment by m986883511** [comment]
> > 一开始的代码在这里 [1d62237/core/config.py#r126889427](https://github.com/AnsGoo/PyPicGo/commit/1d62237a3b1ad74c3cb176b8e87c66c3e7f5639d/core/config.py#r126889427)
> > 基于什么考虑现在去掉了呢
> 
> 因为Pydantic 太大了,验证与否对于一个插件包意义不大，如果能写成插件库，相信大家都是经过深思熟虑的验证，pydantic 更多的是对用户的输入进行验证

您说的很有道理

**Comment by m986883511** [comment]
> 

不懂前端，洋葱模型受教了

**Comment by m986883511** [comment]
我包了一层api，两次同时复制一个本地文件在ob中粘贴，第一次成功，第二次上传也成功，但是删除本地临时文件报错，应该是个bug，删除之前应该检查下。

```shell
import json
import os
import shutil

from PIL import ImageGrab
from PIL.PngImagePlugin import PngImageFile
from flask import Flask, request
from pypicgo.core.config import Settings
from pypicgo.core.execute import create_uploader
from pypicgo.core.logger import logger
from pypicgo import BASE_DIR

app = Flask(__name__)


def run_action(uploader_name, filepath):
    settings = Settings(uploader_name=uploader_name)
    uploader = settings.uploader_class
    uploader_config = settings.uploader_config
    plugins = settings.plugins
    with create_uploader(uploader, uploader_config, plugins) as uploader:
        logger.info('upload start')
        logger.info(f'upload file [{filepath}]')
        uploader.do(filepath)
        remote_url = uploader.result.remote_url
        print(f'remote_url is {remote_url}')
        return remote_url


def copy_image(src):
    file_extension = os.path.splitext(src)[1]
    if file_extension.lower() not in ('.png', '.jpg', '.jpeg', '.bmp'):
        raise Exception(f'not support file_extension={file_extension}')
    tmp_image = os.path.join(BASE_DIR, f'tmp{file_extension}')
    shutil.copy(src, tmp_image)
    print(f'tmp_image path is {tmp_image}')
    return tmp_image


@app.route('/upload', methods=['POST', 'GET'])
def login():
    get_data = request.get_data()
    print(f"get_data={get_data}")
    image = ImageGrab.grabclipboard()
    print(image)

    if isinstance(image, PngImageFile):
        image.save('tmp.png')
        path = './tmp.png'
    elif isinstance(image, list):
        path = image[0]
        path = copy_image(path)
    else:
        raise Exception(f'can not get path, image clipboard is {image}')

    remote_url = run_action('gitee', path)
    data = {'success': True, 'result': remote_url}
    return json.dumps(data, ensure_ascii=False)


if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=36677)

```

日志

```shell
(py38) PS Z:\code\mine\cs-picgo-server\src\cs_picgo_server>
(py38) PS Z:\code\mine\cs-picgo-server\src\cs_picgo_server> python .\app.py
 * Serving Flask app 'app'
 * Debug mode: on
2023-09-12 15:02:15,504 - werkzeug - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:36677
 * Running on http://192.168.1.102:36677
2023-09-12 15:02:15,504 - werkzeug - INFO - Press CTRL+C to quit
2023-09-12 15:02:15,515 - werkzeug - INFO -  * Restarting with watchdog (windowsapi)
2023-09-12 15:02:16,135 - werkzeug - WARNING -  * Debugger is active!
2023-09-12 15:02:16,143 - werkzeug - INFO -  * Debugger PIN: 648-331-011
get_data=b''
['C:\\Users\\one\\Pictures\\Screenshots\\屏幕截图 2023-09-11 201502.png']
tmp_image path is C:\Users\one\.PyPicGo\tmp.png
2023-09-12 15:02:33,704 - pypicgo - INFO - load config successfully
2023-09-12 15:02:33,705 - pypicgo - INFO - create uploader successfully
2023-09-12 15:02:33,727 - pypicgo - INFO - loader plugins successfully
2023-09-12 15:02:33,728 - pypicgo - INFO - upload start
2023-09-12 15:02:33,728 - pypicgo - INFO - upload file [C:\Users\one\.PyPicGo\tmp.png]
2023-09-12 15:02:33,728 - pypicgo - INFO - uploadfile create successfully
2023-09-12 15:02:33,733 - pypicgo - INFO - plugins [ReName] execute successfully
2023-09-12 15:02:33,747 - pypicgo - INFO - plugins [compress] execute successfully
2023-09-12 15:02:35,616 - pypicgo - INFO - plugins [Notify] execute successfully
remote_url is https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912150233-tmp.png
Upload Success:
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912150233-tmp.png
2023-09-12 15:02:35,616 - pypicgo - INFO - plugins [Typora] execute successfully
2023-09-12 15:02:35,618 - werkzeug - INFO - 127.0.0.1 - - [12/Sep/2023 15:02:35] "POST /upload HTTP/1.1" 200 -
get_data=b''
['C:\\Users\\one\\Pictures\\Screenshots\\屏幕截图 2023-09-11 201502.png']
tmp_image path is C:\Users\one\.PyPicGo\tmp.png
2023-09-12 15:02:55,218 - pypicgo - INFO - load config successfully
2023-09-12 15:02:55,219 - pypicgo - INFO - create uploader successfully
2023-09-12 15:02:55,219 - pypicgo - INFO - loader plugins successfully
2023-09-12 15:02:55,219 - pypicgo - INFO - upload start
2023-09-12 15:02:55,219 - pypicgo - INFO - upload file [C:\Users\one\.PyPicGo\tmp.png]
2023-09-12 15:02:55,220 - pypicgo - INFO - uploadfile create successfully
2023-09-12 15:02:55,225 - pypicgo - INFO - plugins [ReName] execute successfully
2023-09-12 15:02:55,236 - pypicgo - INFO - plugins [compress] execute successfully
2023-09-12 15:02:57,102 - pypicgo - INFO - plugins [Notify] execute successfully
remote_url is https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912150255-tmp.png
Upload Success:
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912150233-tmp.png
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912150255-tmp.png
2023-09-12 15:02:57,103 - pypicgo - INFO - plugins [Typora] execute successfully
2023-09-12 15:02:57,135 - werkzeug - INFO - 127.0.0.1 - - [12/Sep/2023 15:02:57] "POST /upload HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\one\.conda\envs\py38\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\one\.conda\envs\py38\lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
    remote_url = run_action('gitee', path)
  File "Z:\code\mine\cs-picgo-server\src\cs_picgo_server\app.py", line 27, in run_action
    return remote_url
  File "C:\Users\one\.conda\envs\py38\lib\site-packages\pypicgo\core\execute.py", line 22, in __exit__
    self.uploader.final()
  File "C:\Users\one\.conda\envs\py38\lib\site-packages\pypicgo\core\base\uploader.py", line 112, in final
    self.clean_tempfile(result.file)
  File "C:\Users\one\.conda\envs\py38\lib\site-packages\pypicgo\core\base\uploader.py", line 107, in clean_tempfile
    os.remove(file.tempfile.resolve())
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\one\\.conda\\envs\\py38\\Lib\\site-packages\\pypicgo\\plugins\\compress\\temp\\tmp.png'


```

**Comment by m986883511** [comment]
https://github.com/m986883511/cs-picgo-server/blob/main/src/cs_picgo_server/app.py
这是我的代码，我发现多次上传，result堆积结果了


```shell
(py38) PS Z:\code\mine\cs-picgo-server> cs-picgo-server.exe      
 * Serving Flask app 'cs_picgo_server.app'
 * Debug mode: on
2023-09-12 15:39:00,884 - werkzeug - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.      
 * Running on http://127.0.0.1:36677
2023-09-12 15:39:00,885 - werkzeug - INFO - Press CTRL+C to quit
2023-09-12 15:39:00,895 - werkzeug - INFO -  * Restarting with watchdog (windowsapi)
2023-09-12 15:39:01,544 - werkzeug - WARNING -  * Debugger is active!
2023-09-12 15:39:01,553 - werkzeug - INFO -  * Debugger PIN: 648-331-011
2023-09-12 15:39:14,488 - pypicgo - INFO - upload interface get_data=b''
2023-09-12 15:39:14,489 - pypicgo - INFO - upload interface get_image_clipboard=['C:\\Users\\one\\Pictures\\Screenshots\\屏幕截图 2023-09-11 201502.png']
2023-09-12 15:39:14,491 - pypicgo - INFO - tmp_image path is C:\Users\one\.PyPicGo\tmp.png
2023-09-12 15:39:14,631 - pypicgo - INFO - load config successfully
2023-09-12 15:39:14,631 - pypicgo - INFO - create uploader successfully
2023-09-12 15:39:14,652 - pypicgo - INFO - loader plugins successfully
2023-09-12 15:39:14,652 - pypicgo - INFO - upload start
2023-09-12 15:39:14,652 - pypicgo - INFO - upload file [C:\Users\one\.PyPicGo\tmp.png]
2023-09-12 15:39:14,653 - pypicgo - INFO - uploadfile create successfully
2023-09-12 15:39:14,658 - pypicgo - INFO - plugins [ReName] execute successfully
2023-09-12 15:39:14,673 - pypicgo - INFO - plugins [compress] execute successfully
2023-09-12 15:39:16,501 - pypicgo - INFO - plugins [Notify] execute successfully
2023-09-12 15:39:16,502 - pypicgo - INFO - remote_url is https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153914-tmp.png
Upload Success:
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153914-tmp.png
2023-09-12 15:39:16,502 - pypicgo - INFO - plugins [Typora] execute successfully
2023-09-12 15:39:16,504 - werkzeug - INFO - 127.0.0.1 - - [12/Sep/2023 15:39:16] "POST /upload HTTP/1.1" 200 -
2023-09-12 15:39:17,546 - pypicgo - INFO - upload interface get_data=b''
2023-09-12 15:39:17,546 - pypicgo - INFO - upload interface get_image_clipboard=['C:\\Users\\one\\Pictures\\Screenshots\\屏幕截图 2023-09-11 201502.png']
2023-09-12 15:39:17,548 - pypicgo - INFO - tmp_image path is C:\Users\one\.PyPicGo\tmp.png
2023-09-12 15:39:17,549 - pypicgo - INFO - load config successfully
2023-09-12 15:39:17,550 - pypicgo - INFO - create uploader successfully
2023-09-12 15:39:17,550 - pypicgo - INFO - loader plugins successfully
2023-09-12 15:39:17,550 - pypicgo - INFO - upload start
2023-09-12 15:39:17,550 - pypicgo - INFO - upload file [C:\Users\one\.PyPicGo\tmp.png]
2023-09-12 15:39:17,550 - pypicgo - INFO - uploadfile create successfully
2023-09-12 15:39:17,556 - pypicgo - INFO - plugins [ReName] execute successfully
2023-09-12 15:39:17,566 - pypicgo - INFO - plugins [compress] execute successfully
2023-09-12 15:39:19,388 - pypicgo - INFO - plugins [Notify] execute successfully
2023-09-12 15:39:19,388 - pypicgo - INFO - remote_url is https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153917-tmp.png
Upload Success:
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153914-tmp.png
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153917-tmp.png
2023-09-12 15:39:19,389 - pypicgo - INFO - plugins [Typora] execute successfully
2023-09-12 15:39:19,392 - werkzeug - INFO - 127.0.0.1 - - [12/Sep/2023 15:39:19] "POST /upload HTTP/1.1" 200 -
2023-09-12 15:39:20,271 - pypicgo - INFO - upload interface get_data=b''
2023-09-12 15:39:20,271 - pypicgo - INFO - upload interface get_image_clipboard=['C:\\Users\\one\\Pictures\\Screenshots\\屏幕截图 2023-09-11 201502.png']
2023-09-12 15:39:20,273 - pypicgo - INFO - tmp_image path is C:\Users\one\.PyPicGo\tmp.png
2023-09-12 15:39:20,274 - pypicgo - INFO - load config successfully
2023-09-12 15:39:20,275 - pypicgo - INFO - create uploader successfully
2023-09-12 15:39:20,275 - pypicgo - INFO - loader plugins successfully
2023-09-12 15:39:20,275 - pypicgo - INFO - upload start
2023-09-12 15:39:20,275 - pypicgo - INFO - upload file [C:\Users\one\.PyPicGo\tmp.png]
2023-09-12 15:39:20,276 - pypicgo - INFO - uploadfile create successfully
2023-09-12 15:39:20,281 - pypicgo - INFO - plugins [ReName] execute successfully
2023-09-12 15:39:20,290 - pypicgo - INFO - plugins [compress] execute successfully
2023-09-12 15:39:22,196 - pypicgo - INFO - plugins [Notify] execute successfully
2023-09-12 15:39:22,196 - pypicgo - INFO - remote_url is https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153920-tmp.png
Upload Success:
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153914-tmp.png
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153917-tmp.png
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153920-tmp.png
2023-09-12 15:39:22,197 - pypicgo - INFO - plugins [Typora] execute successfully
2023-09-12 15:39:22,201 - werkzeug - INFO - 127.0.0.1 - - [12/Sep/2023 15:39:22] "POST /upload HTTP/1.1" 200 -
2023-09-12 15:39:23,119 - pypicgo - INFO - upload interface get_data=b''
2023-09-12 15:39:23,120 - pypicgo - INFO - upload interface get_image_clipboard=['C:\\Users\\one\\Pictures\\Screenshots\\屏幕截图 2023-09-11 201502.png']
2023-09-12 15:39:23,122 - pypicgo - INFO - tmp_image path is C:\Users\one\.PyPicGo\tmp.png
2023-09-12 15:39:23,123 - pypicgo - INFO - load config successfully
2023-09-12 15:39:23,123 - pypicgo - INFO - create uploader successfully
2023-09-12 15:39:23,123 - pypicgo - INFO - loader plugins successfully
2023-09-12 15:39:23,124 - pypicgo - INFO - upload start
2023-09-12 15:39:23,124 - pypicgo - INFO - upload file [C:\Users\one\.PyPicGo\tmp.png]
2023-09-12 15:39:23,124 - pypicgo - INFO - uploadfile create successfully
2023-09-12 15:39:23,129 - pypicgo - INFO - plugins [ReName] execute successfully
2023-09-12 15:39:23,139 - pypicgo - INFO - plugins [compress] execute successfully
2023-09-12 15:39:25,135 - pypicgo - INFO - plugins [Notify] execute successfully
2023-09-12 15:39:25,136 - pypicgo - INFO - remote_url is https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153923-tmp.png
Upload Success:
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153914-tmp.png
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153917-tmp.png
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153920-tmp.png
https://gitee.com/m986883511/picture-bed/raw/master/PyPicGo/liunx1702291e223e62b1c369dfe8ae720648chenghaiwen20230912153923-tmp.png
2023-09-12 15:39:25,136 - pypicgo - INFO - plugins [Typora] execute successfully
2023-09-12 15:39:25,140 - werkzeug - INFO - 127.0.0.1 - - [12/Sep/2023 15:39:25] "POST /upload HTTP/1.1" 200 -

```

**Comment by m986883511** [comment]
```python
class CommonUploader(BaseUploader):
    type = 'uploader'
    _plugins: List[PluginModel] = []
    _after_plugins: List[Any] = []
    _before_plugins: List[Any] = []
    _final_plugins: List[Any] = []
    file = None
    result = None
    results: List[Result] = []
```

类成员变量results等同于全局变量，在这里存结果是不是有点不好

**Comment by AnsGoo** [comment]
> ```python
> class CommonUploader(BaseUploader):
>     type = 'uploader'
>     _plugins: List[PluginModel] = []
>     _after_plugins: List[Any] = []
>     _before_plugins: List[Any] = []
>     _final_plugins: List[Any] = []
>     file = None
>     result = None
>     results: List[Result] = []
> ```
> 
> 类成员变量results等同于全局变量，在这里存结果是不是有点不好

你的使用方式不是我的设想的场景，你是这个Web程序，我是命令行程序，命令行程序每次打开都是新的类对象实例

**Comment by m986883511** [comment]
是的，调用之前我设置为空列表就好了
